### ISSUE TITLE
Connection reset by peer error

### ISSUE THREAD

**Issue by sfmcfar1960** [wickerwaka/russound_rio#1]
HI, just started working with the Russound RIO module and I have a problem.  Approximately once a day I get the following error from HASS:

2019-01-23 01:17:19 ERROR (MainThread) [russound] Unhandled exception in IO loop
Traceback (most recent call last):
File "/srv/homeassistant/lib/python3.6/site-packages/russound_rio/rio.py", line 171, in _ioloop
    response = net_future.result()
File "/usr/lib/python3.6/asyncio/streams.py", line 488, in readline
    line = yield from self.readuntil(sep)
File "/usr/lib/python3.6/asyncio/streams.py", line 581, in readuntil
    yield from self._wait_for_data('readuntil')
File "/usr/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
File "/usr/lib/python3.6/asyncio/selector_events.py", line 725, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

which causes the HASS front ends to stop communicating with my MCA-C6.  The only way to fix it so far is to reboot HASS.  Any suggestions?

Thanks

Stan McFarland

**Comment by shinyshoes16** [comment]
I'm getting a similar error.  Any comments @wickerwaka ?  Here is my log file entry:

Logger: russound
Source: /usr/local/lib/python3.7/site-packages/russound_rio/rio.py:209
First occurred: June 28, 2020, 10:45:28 AM (1 occurrences)
Last logged: June 28, 2020, 10:45:28 AM

Unhandled exception in IO loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/russound_rio/rio.py", line 172, in _ioloop
    response = net_future.result()
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 496, in readline
    line = await self.readuntil(sep)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 588, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 814, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by sfmcfar1960** [comment]
The only thing I found that worked was to create an automation that pinged
the Russound every hour.   Otherwise the connection times out.

Stan

**Comment by shinyshoes16** [comment]
Thanks Stan,   I've implemented that hack this morning and so far so good.  This issue still needs to be resolved however as it is ridiculous that we need to rely on automations to keep the connection alive.  Thanks for your help.

**Comment by wickerwaka** [comment]
> The only thing I found that worked was to create an automation that pinged the Russound every hour. Otherwise the connection times out. Stan

I'm not seeing this issue with my MCA-88X. @sfmcfar1960 what are you doing to ping it? Just making a service call?

**Comment by sfmcfar1960** [comment]
Yes.  Was retrieving the volume from the Russound every hour.

Stan

**Comment by joshlawless** [comment]
Those of you who set up an automation to keep your Russound alive - what "action" did you use?  looking through the service calls available, I don't see anything that would query volume, only those that set volume (which I worry would turn on a zone unexpectedly)
