### ISSUE TITLE
Not compatible with Python 3.10?

### ISSUE THREAD

**Issue by neillt** [wickerwaka/russound_rio#10]
Trying to use the russound_rio library as part of Home Assistant 2022.7, and I believe that they have switched to Python 3.10.5.

Now, when invoking the rio library, it would appear that the Loop parameters are making it angry:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/src/homeassistant/homeassistant/components/russound_rio/media_player.py", line 46, in async_setup_platform
    russ = Russound(hass.loop, host, port)
  File "/usr/local/lib/python3.10/site-packages/russound_rio/rio.py", line 71, in __init__
    self._cmd_queue = asyncio.Queue(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "/usr/local/lib/python3.10/asyncio/mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary`

The library does not talk to any of my Russound amps, effectively breaking the integration.

I am not a Python dev by any means, so I don't know how hard it would be to re-code this to work with 3.10.

**Comment by wickerwaka** [comment]
Merged PR and released a new version of the module: https://github.com/wickerwaka/russound_rio/releases/tag/v0.1.8
