### ISSUE TITLE
Python 3.11 incompatibility ( async coroutines removed )

### ISSUE THREAD

**Issue by chphilli** [wickerwaka/russound_rio#13]
I was trying to use this integration in the latest Home Assistant release (2023.6) and encountered this error:

> 2023-06-08 17:10:32 home-assistant  | 2023-06-08 17:10:32.772 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform homeassistant.components.russound_rio.media_player
> 2023-06-08 17:10:32 home-assistant  | Traceback (most recent call last):
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
> 2023-06-08 17:10:32 home-assistant  |     cache[full_name] = self._import_platform(platform_name)
> 2023-06-08 17:10:32 home-assistant  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
> 2023-06-08 17:10:32 home-assistant  |     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
> 2023-06-08 17:10:32 home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
> 2023-06-08 17:10:32 home-assistant  |     return _bootstrap._gcd_import(name[level:], package, level)
> 2023-06-08 17:10:32 home-assistant  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
> 2023-06-08 17:10:32 home-assistant  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/src/homeassistant/homeassistant/components/russound_rio/media_player.py", line 4, in <module>
> 2023-06-08 17:10:32 home-assistant  |     from russound_rio import Russound
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/site-packages/russound_rio/__init__.py", line 1, in <module>
> 2023-06-08 17:10:32 home-assistant  |     from .rio import (
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/site-packages/russound_rio/rio.py", line 59, in <module>
> 2023-06-08 17:10:32 home-assistant  |     class Russound:
> 2023-06-08 17:10:32 home-assistant  |   File "/usr/local/lib/python3.11/site-packages/russound_rio/rio.py", line 157, in Russound
> 2023-06-08 17:10:32 home-assistant  |     @asyncio.coroutine
> 2023-06-08 17:10:32 home-assistant  |      ^^^^^^^^^^^^^^^^^
> 2023-06-08 17:10:32 home-assistant  | AttributeError: module 'asyncio' has no attribute 'coroutine'

This appears to be an incompatibility with async semantics in Python 3.11: https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11

**Comment by chphilli** [comment]
For reference, here's the issue in Home Assistant: https://github.com/home-assistant/core/issues/94295

**Comment by chphilli** [comment]
@wickerwaka I've got a fix for this in #14 , would love if you could take a look.
